/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments/$slug'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTournamentsRouteImport } from './routes/admin/tournaments'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminMigrateLogosRouteImport } from './routes/admin/migrate-logos'
import { Route as AdminTournamentsIndexRouteImport } from './routes/admin/tournaments/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLiveMatchIdRouteImport } from './routes/admin/live/$matchId'
import { Route as AdminTournamentsTournamentIdMatchesRouteImport } from './routes/admin/tournaments/$tournamentId/matches'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TournamentsRoute,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TournamentsRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/admin/tournaments',
  path: '/admin/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrateLogosRoute = AdminMigrateLogosRouteImport.update({
  id: '/admin/migrate-logos',
  path: '/admin/migrate-logos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsIndexRoute = AdminTournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTournamentsRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveMatchIdRoute = AdminLiveMatchIdRouteImport.update({
  id: '/admin/live/$matchId',
  path: '/admin/live/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsTournamentIdMatchesRoute =
  AdminTournamentsTournamentIdMatchesRouteImport.update({
    id: '/$tournamentId/matches',
    path: '/$tournamentId/matches',
    getParentRoute: () => AdminTournamentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/admin/migrate-logos': typeof AdminMigrateLogosRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/live/$matchId': typeof AdminLiveMatchIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/tournaments/$tournamentId/matches': typeof AdminTournamentsTournamentIdMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/admin/migrate-logos': typeof AdminMigrateLogosRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/live/$matchId': typeof AdminLiveMatchIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
  '/admin/tournaments/$tournamentId/matches': typeof AdminTournamentsTournamentIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/admin/migrate-logos': typeof AdminMigrateLogosRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/live/$matchId': typeof AdminLiveMatchIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/tournaments/$tournamentId/matches': typeof AdminTournamentsTournamentIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/landing'
    | '/leaderboard'
    | '/login'
    | '/tournaments'
    | '/admin/migrate-logos'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/teams/$teamId'
    | '/tournaments/$slug'
    | '/tournaments/'
    | '/admin/live/$matchId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/tournaments/'
    | '/admin/tournaments/$tournamentId/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/landing'
    | '/leaderboard'
    | '/login'
    | '/admin/migrate-logos'
    | '/admin/teams'
    | '/admin/users'
    | '/teams/$teamId'
    | '/tournaments/$slug'
    | '/tournaments'
    | '/admin/live/$matchId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/tournaments'
    | '/admin/tournaments/$tournamentId/matches'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/landing'
    | '/leaderboard'
    | '/login'
    | '/tournaments'
    | '/admin/migrate-logos'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/teams/$teamId'
    | '/tournaments/$slug'
    | '/tournaments/'
    | '/admin/live/$matchId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/tournaments/'
    | '/admin/tournaments/$tournamentId/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  AdminMigrateLogosRoute: typeof AdminMigrateLogosRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  AdminLiveMatchIdRoute: typeof AdminLiveMatchIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migrate-logos': {
      id: '/admin/migrate-logos'
      path: '/admin/migrate-logos'
      fullPath: '/admin/migrate-logos'
      preLoaderRoute: typeof AdminMigrateLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/': {
      id: '/admin/tournaments/'
      path: '/'
      fullPath: '/admin/tournaments/'
      preLoaderRoute: typeof AdminTournamentsIndexRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live/$matchId': {
      id: '/admin/live/$matchId'
      path: '/admin/live/$matchId'
      fullPath: '/admin/live/$matchId'
      preLoaderRoute: typeof AdminLiveMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$tournamentId/matches': {
      id: '/admin/tournaments/$tournamentId/matches'
      path: '/$tournamentId/matches'
      fullPath: '/admin/tournaments/$tournamentId/matches'
      preLoaderRoute: typeof AdminTournamentsTournamentIdMatchesRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
  }
}

interface TournamentsRouteChildren {
  TournamentsSlugRoute: typeof TournamentsSlugRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsSlugRoute: TournamentsSlugRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

interface AdminTournamentsRouteChildren {
  AdminTournamentsIndexRoute: typeof AdminTournamentsIndexRoute
  AdminTournamentsTournamentIdMatchesRoute: typeof AdminTournamentsTournamentIdMatchesRoute
}

const AdminTournamentsRouteChildren: AdminTournamentsRouteChildren = {
  AdminTournamentsIndexRoute: AdminTournamentsIndexRoute,
  AdminTournamentsTournamentIdMatchesRoute:
    AdminTournamentsTournamentIdMatchesRoute,
}

const AdminTournamentsRouteWithChildren =
  AdminTournamentsRoute._addFileChildren(AdminTournamentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  AdminMigrateLogosRoute: AdminMigrateLogosRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTournamentsRoute: AdminTournamentsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  AdminLiveMatchIdRoute: AdminLiveMatchIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
