/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTournamentsRouteImport } from './routes/admin/tournaments'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminTournamentsIndexRouteImport } from './routes/admin/tournaments/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLiveMatchIdRouteImport } from './routes/admin/live/$matchId'
import { Route as AdminTournamentsTournamentIdMatchesRouteImport } from './routes/admin/tournaments/$tournamentId/matches'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/admin/tournaments',
  path: '/admin/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsIndexRoute = AdminTournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTournamentsRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveMatchIdRoute = AdminLiveMatchIdRouteImport.update({
  id: '/admin/live/$matchId',
  path: '/admin/live/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsTournamentIdMatchesRoute =
  AdminTournamentsTournamentIdMatchesRouteImport.update({
    id: '/$tournamentId/matches',
    path: '/$tournamentId/matches',
    getParentRoute: () => AdminTournamentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/live/$matchId': typeof AdminLiveMatchIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/tournaments/$tournamentId/matches': typeof AdminTournamentsTournamentIdMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/live/$matchId': typeof AdminLiveMatchIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
  '/admin/tournaments/$tournamentId/matches': typeof AdminTournamentsTournamentIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/live/$matchId': typeof AdminLiveMatchIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/tournaments/$tournamentId/matches': typeof AdminTournamentsTournamentIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/live/$matchId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/tournaments/'
    | '/admin/tournaments/$tournamentId/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/live/$matchId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/tournaments'
    | '/admin/tournaments/$tournamentId/matches'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/live/$matchId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/tournaments/'
    | '/admin/tournaments/$tournamentId/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminLiveMatchIdRoute: typeof AdminLiveMatchIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/': {
      id: '/admin/tournaments/'
      path: '/'
      fullPath: '/admin/tournaments/'
      preLoaderRoute: typeof AdminTournamentsIndexRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live/$matchId': {
      id: '/admin/live/$matchId'
      path: '/admin/live/$matchId'
      fullPath: '/admin/live/$matchId'
      preLoaderRoute: typeof AdminLiveMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$tournamentId/matches': {
      id: '/admin/tournaments/$tournamentId/matches'
      path: '/$tournamentId/matches'
      fullPath: '/admin/tournaments/$tournamentId/matches'
      preLoaderRoute: typeof AdminTournamentsTournamentIdMatchesRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
  }
}

interface AdminTournamentsRouteChildren {
  AdminTournamentsIndexRoute: typeof AdminTournamentsIndexRoute
  AdminTournamentsTournamentIdMatchesRoute: typeof AdminTournamentsTournamentIdMatchesRoute
}

const AdminTournamentsRouteChildren: AdminTournamentsRouteChildren = {
  AdminTournamentsIndexRoute: AdminTournamentsIndexRoute,
  AdminTournamentsTournamentIdMatchesRoute:
    AdminTournamentsTournamentIdMatchesRoute,
}

const AdminTournamentsRouteWithChildren =
  AdminTournamentsRoute._addFileChildren(AdminTournamentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTournamentsRoute: AdminTournamentsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminLiveMatchIdRoute: AdminLiveMatchIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
