/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTournamentsRouteImport } from './routes/$lang/tournaments'
import { Route as LangProfileRouteImport } from './routes/$lang/profile'
import { Route as LangMyBetsRouteImport } from './routes/$lang/my-bets'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangLeaderboardRouteImport } from './routes/$lang/leaderboard'
import { Route as LangLandingRouteImport } from './routes/$lang/landing'
import { Route as LangDashboardRouteImport } from './routes/$lang/dashboard'
import { Route as Lang_layoutRouteImport } from './routes/$lang/__layout'
import { Route as LangTournamentsIndexRouteImport } from './routes/$lang/tournaments/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LangUsersUserIdRouteImport } from './routes/$lang/users/$userId'
import { Route as LangTournamentsSlugRouteImport } from './routes/$lang/tournaments/$slug'
import { Route as LangTeamsTeamIdRouteImport } from './routes/$lang/teams/$teamId'
import { Route as LangAdminUsersRouteImport } from './routes/$lang/admin/users'
import { Route as LangAdminTournamentsRouteImport } from './routes/$lang/admin/tournaments'
import { Route as LangAdminTeamsRouteImport } from './routes/$lang/admin/teams'
import { Route as LangAdminMigrateLogosRouteImport } from './routes/$lang/admin/migrate-logos'
import { Route as LangAdminCompensationsRouteImport } from './routes/$lang/admin/compensations'
import { Route as LangAdminTournamentsIndexRouteImport } from './routes/$lang/admin/tournaments/index'
import { Route as LangAdminLiveMatchIdRouteImport } from './routes/$lang/admin/live/$matchId'
import { Route as LangAdminTournamentsTournamentIdMatchesRouteImport } from './routes/$lang/admin/tournaments/$tournamentId/matches'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTournamentsRoute = LangTournamentsRouteImport.update({
  id: '/$lang/tournaments',
  path: '/$lang/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProfileRoute = LangProfileRouteImport.update({
  id: '/$lang/profile',
  path: '/$lang/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LangMyBetsRoute = LangMyBetsRouteImport.update({
  id: '/$lang/my-bets',
  path: '/$lang/my-bets',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/$lang/login',
  path: '/$lang/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLeaderboardRoute = LangLeaderboardRouteImport.update({
  id: '/$lang/leaderboard',
  path: '/$lang/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLandingRoute = LangLandingRouteImport.update({
  id: '/$lang/landing',
  path: '/$lang/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDashboardRoute = LangDashboardRouteImport.update({
  id: '/$lang/dashboard',
  path: '/$lang/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Lang_layoutRoute = Lang_layoutRouteImport.update({
  id: '/$lang/__layout',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTournamentsIndexRoute = LangTournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangTournamentsRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangUsersUserIdRoute = LangUsersUserIdRouteImport.update({
  id: '/$lang/users/$userId',
  path: '/$lang/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTournamentsSlugRoute = LangTournamentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangTournamentsRoute,
} as any)
const LangTeamsTeamIdRoute = LangTeamsTeamIdRouteImport.update({
  id: '/$lang/teams/$teamId',
  path: '/$lang/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAdminUsersRoute = LangAdminUsersRouteImport.update({
  id: '/$lang/admin/users',
  path: '/$lang/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAdminTournamentsRoute = LangAdminTournamentsRouteImport.update({
  id: '/$lang/admin/tournaments',
  path: '/$lang/admin/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAdminTeamsRoute = LangAdminTeamsRouteImport.update({
  id: '/$lang/admin/teams',
  path: '/$lang/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAdminMigrateLogosRoute = LangAdminMigrateLogosRouteImport.update({
  id: '/$lang/admin/migrate-logos',
  path: '/$lang/admin/migrate-logos',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAdminCompensationsRoute = LangAdminCompensationsRouteImport.update({
  id: '/$lang/admin/compensations',
  path: '/$lang/admin/compensations',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAdminTournamentsIndexRoute =
  LangAdminTournamentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAdminTournamentsRoute,
  } as any)
const LangAdminLiveMatchIdRoute = LangAdminLiveMatchIdRouteImport.update({
  id: '/$lang/admin/live/$matchId',
  path: '/$lang/admin/live/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAdminTournamentsTournamentIdMatchesRoute =
  LangAdminTournamentsTournamentIdMatchesRouteImport.update({
    id: '/$tournamentId/matches',
    path: '/$tournamentId/matches',
    getParentRoute: () => LangAdminTournamentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/$lang': typeof Lang_layoutRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/landing': typeof LangLandingRoute
  '/$lang/leaderboard': typeof LangLeaderboardRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/my-bets': typeof LangMyBetsRoute
  '/$lang/profile': typeof LangProfileRoute
  '/$lang/tournaments': typeof LangTournamentsRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/compensations': typeof LangAdminCompensationsRoute
  '/$lang/admin/migrate-logos': typeof LangAdminMigrateLogosRoute
  '/$lang/admin/teams': typeof LangAdminTeamsRoute
  '/$lang/admin/tournaments': typeof LangAdminTournamentsRouteWithChildren
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/teams/$teamId': typeof LangTeamsTeamIdRoute
  '/$lang/tournaments/$slug': typeof LangTournamentsSlugRoute
  '/$lang/users/$userId': typeof LangUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$lang/tournaments/': typeof LangTournamentsIndexRoute
  '/$lang/admin/live/$matchId': typeof LangAdminLiveMatchIdRoute
  '/$lang/admin/tournaments/': typeof LangAdminTournamentsIndexRoute
  '/$lang/admin/tournaments/$tournamentId/matches': typeof LangAdminTournamentsTournamentIdMatchesRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/landing': typeof LangLandingRoute
  '/$lang/leaderboard': typeof LangLeaderboardRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/my-bets': typeof LangMyBetsRoute
  '/$lang/profile': typeof LangProfileRoute
  '/$lang/admin/compensations': typeof LangAdminCompensationsRoute
  '/$lang/admin/migrate-logos': typeof LangAdminMigrateLogosRoute
  '/$lang/admin/teams': typeof LangAdminTeamsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/teams/$teamId': typeof LangTeamsTeamIdRoute
  '/$lang/tournaments/$slug': typeof LangTournamentsSlugRoute
  '/$lang/users/$userId': typeof LangUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$lang/tournaments': typeof LangTournamentsIndexRoute
  '/$lang/admin/live/$matchId': typeof LangAdminLiveMatchIdRoute
  '/$lang/admin/tournaments': typeof LangAdminTournamentsIndexRoute
  '/$lang/admin/tournaments/$tournamentId/matches': typeof LangAdminTournamentsTournamentIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/$lang/__layout': typeof Lang_layoutRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/landing': typeof LangLandingRoute
  '/$lang/leaderboard': typeof LangLeaderboardRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/my-bets': typeof LangMyBetsRoute
  '/$lang/profile': typeof LangProfileRoute
  '/$lang/tournaments': typeof LangTournamentsRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/compensations': typeof LangAdminCompensationsRoute
  '/$lang/admin/migrate-logos': typeof LangAdminMigrateLogosRoute
  '/$lang/admin/teams': typeof LangAdminTeamsRoute
  '/$lang/admin/tournaments': typeof LangAdminTournamentsRouteWithChildren
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/teams/$teamId': typeof LangTeamsTeamIdRoute
  '/$lang/tournaments/$slug': typeof LangTournamentsSlugRoute
  '/$lang/users/$userId': typeof LangUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$lang/tournaments/': typeof LangTournamentsIndexRoute
  '/$lang/admin/live/$matchId': typeof LangAdminLiveMatchIdRoute
  '/$lang/admin/tournaments/': typeof LangAdminTournamentsIndexRoute
  '/$lang/admin/tournaments/$tournamentId/matches': typeof LangAdminTournamentsTournamentIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/$lang'
    | '/$lang/dashboard'
    | '/$lang/landing'
    | '/$lang/leaderboard'
    | '/$lang/login'
    | '/$lang/my-bets'
    | '/$lang/profile'
    | '/$lang/tournaments'
    | '/$lang/'
    | '/$lang/admin/compensations'
    | '/$lang/admin/migrate-logos'
    | '/$lang/admin/teams'
    | '/$lang/admin/tournaments'
    | '/$lang/admin/users'
    | '/$lang/teams/$teamId'
    | '/$lang/tournaments/$slug'
    | '/$lang/users/$userId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$lang/tournaments/'
    | '/$lang/admin/live/$matchId'
    | '/$lang/admin/tournaments/'
    | '/$lang/admin/tournaments/$tournamentId/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/$lang'
    | '/$lang/dashboard'
    | '/$lang/landing'
    | '/$lang/leaderboard'
    | '/$lang/login'
    | '/$lang/my-bets'
    | '/$lang/profile'
    | '/$lang/admin/compensations'
    | '/$lang/admin/migrate-logos'
    | '/$lang/admin/teams'
    | '/$lang/admin/users'
    | '/$lang/teams/$teamId'
    | '/$lang/tournaments/$slug'
    | '/$lang/users/$userId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$lang/tournaments'
    | '/$lang/admin/live/$matchId'
    | '/$lang/admin/tournaments'
    | '/$lang/admin/tournaments/$tournamentId/matches'
  id:
    | '__root__'
    | '/$'
    | '/$lang/__layout'
    | '/$lang/dashboard'
    | '/$lang/landing'
    | '/$lang/leaderboard'
    | '/$lang/login'
    | '/$lang/my-bets'
    | '/$lang/profile'
    | '/$lang/tournaments'
    | '/$lang/'
    | '/$lang/admin/compensations'
    | '/$lang/admin/migrate-logos'
    | '/$lang/admin/teams'
    | '/$lang/admin/tournaments'
    | '/$lang/admin/users'
    | '/$lang/teams/$teamId'
    | '/$lang/tournaments/$slug'
    | '/$lang/users/$userId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$lang/tournaments/'
    | '/$lang/admin/live/$matchId'
    | '/$lang/admin/tournaments/'
    | '/$lang/admin/tournaments/$tournamentId/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  Lang_layoutRoute: typeof Lang_layoutRoute
  LangDashboardRoute: typeof LangDashboardRoute
  LangLandingRoute: typeof LangLandingRoute
  LangLeaderboardRoute: typeof LangLeaderboardRoute
  LangLoginRoute: typeof LangLoginRoute
  LangMyBetsRoute: typeof LangMyBetsRoute
  LangProfileRoute: typeof LangProfileRoute
  LangTournamentsRoute: typeof LangTournamentsRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
  LangAdminCompensationsRoute: typeof LangAdminCompensationsRoute
  LangAdminMigrateLogosRoute: typeof LangAdminMigrateLogosRoute
  LangAdminTeamsRoute: typeof LangAdminTeamsRoute
  LangAdminTournamentsRoute: typeof LangAdminTournamentsRouteWithChildren
  LangAdminUsersRoute: typeof LangAdminUsersRoute
  LangTeamsTeamIdRoute: typeof LangTeamsTeamIdRoute
  LangUsersUserIdRoute: typeof LangUsersUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  LangAdminLiveMatchIdRoute: typeof LangAdminLiveMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/tournaments': {
      id: '/$lang/tournaments'
      path: '/$lang/tournaments'
      fullPath: '/$lang/tournaments'
      preLoaderRoute: typeof LangTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/profile': {
      id: '/$lang/profile'
      path: '/$lang/profile'
      fullPath: '/$lang/profile'
      preLoaderRoute: typeof LangProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/my-bets': {
      id: '/$lang/my-bets'
      path: '/$lang/my-bets'
      fullPath: '/$lang/my-bets'
      preLoaderRoute: typeof LangMyBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/$lang/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/leaderboard': {
      id: '/$lang/leaderboard'
      path: '/$lang/leaderboard'
      fullPath: '/$lang/leaderboard'
      preLoaderRoute: typeof LangLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/landing': {
      id: '/$lang/landing'
      path: '/$lang/landing'
      fullPath: '/$lang/landing'
      preLoaderRoute: typeof LangLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/dashboard': {
      id: '/$lang/dashboard'
      path: '/$lang/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/__layout': {
      id: '/$lang/__layout'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof Lang_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/tournaments/': {
      id: '/$lang/tournaments/'
      path: '/'
      fullPath: '/$lang/tournaments/'
      preLoaderRoute: typeof LangTournamentsIndexRouteImport
      parentRoute: typeof LangTournamentsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/users/$userId': {
      id: '/$lang/users/$userId'
      path: '/$lang/users/$userId'
      fullPath: '/$lang/users/$userId'
      preLoaderRoute: typeof LangUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/tournaments/$slug': {
      id: '/$lang/tournaments/$slug'
      path: '/$slug'
      fullPath: '/$lang/tournaments/$slug'
      preLoaderRoute: typeof LangTournamentsSlugRouteImport
      parentRoute: typeof LangTournamentsRoute
    }
    '/$lang/teams/$teamId': {
      id: '/$lang/teams/$teamId'
      path: '/$lang/teams/$teamId'
      fullPath: '/$lang/teams/$teamId'
      preLoaderRoute: typeof LangTeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/admin/users': {
      id: '/$lang/admin/users'
      path: '/$lang/admin/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/admin/tournaments': {
      id: '/$lang/admin/tournaments'
      path: '/$lang/admin/tournaments'
      fullPath: '/$lang/admin/tournaments'
      preLoaderRoute: typeof LangAdminTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/admin/teams': {
      id: '/$lang/admin/teams'
      path: '/$lang/admin/teams'
      fullPath: '/$lang/admin/teams'
      preLoaderRoute: typeof LangAdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/admin/migrate-logos': {
      id: '/$lang/admin/migrate-logos'
      path: '/$lang/admin/migrate-logos'
      fullPath: '/$lang/admin/migrate-logos'
      preLoaderRoute: typeof LangAdminMigrateLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/admin/compensations': {
      id: '/$lang/admin/compensations'
      path: '/$lang/admin/compensations'
      fullPath: '/$lang/admin/compensations'
      preLoaderRoute: typeof LangAdminCompensationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/admin/tournaments/': {
      id: '/$lang/admin/tournaments/'
      path: '/'
      fullPath: '/$lang/admin/tournaments/'
      preLoaderRoute: typeof LangAdminTournamentsIndexRouteImport
      parentRoute: typeof LangAdminTournamentsRoute
    }
    '/$lang/admin/live/$matchId': {
      id: '/$lang/admin/live/$matchId'
      path: '/$lang/admin/live/$matchId'
      fullPath: '/$lang/admin/live/$matchId'
      preLoaderRoute: typeof LangAdminLiveMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/admin/tournaments/$tournamentId/matches': {
      id: '/$lang/admin/tournaments/$tournamentId/matches'
      path: '/$tournamentId/matches'
      fullPath: '/$lang/admin/tournaments/$tournamentId/matches'
      preLoaderRoute: typeof LangAdminTournamentsTournamentIdMatchesRouteImport
      parentRoute: typeof LangAdminTournamentsRoute
    }
  }
}

interface LangTournamentsRouteChildren {
  LangTournamentsSlugRoute: typeof LangTournamentsSlugRoute
  LangTournamentsIndexRoute: typeof LangTournamentsIndexRoute
}

const LangTournamentsRouteChildren: LangTournamentsRouteChildren = {
  LangTournamentsSlugRoute: LangTournamentsSlugRoute,
  LangTournamentsIndexRoute: LangTournamentsIndexRoute,
}

const LangTournamentsRouteWithChildren = LangTournamentsRoute._addFileChildren(
  LangTournamentsRouteChildren,
)

interface LangAdminTournamentsRouteChildren {
  LangAdminTournamentsIndexRoute: typeof LangAdminTournamentsIndexRoute
  LangAdminTournamentsTournamentIdMatchesRoute: typeof LangAdminTournamentsTournamentIdMatchesRoute
}

const LangAdminTournamentsRouteChildren: LangAdminTournamentsRouteChildren = {
  LangAdminTournamentsIndexRoute: LangAdminTournamentsIndexRoute,
  LangAdminTournamentsTournamentIdMatchesRoute:
    LangAdminTournamentsTournamentIdMatchesRoute,
}

const LangAdminTournamentsRouteWithChildren =
  LangAdminTournamentsRoute._addFileChildren(LangAdminTournamentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  Lang_layoutRoute: Lang_layoutRoute,
  LangDashboardRoute: LangDashboardRoute,
  LangLandingRoute: LangLandingRoute,
  LangLeaderboardRoute: LangLeaderboardRoute,
  LangLoginRoute: LangLoginRoute,
  LangMyBetsRoute: LangMyBetsRoute,
  LangProfileRoute: LangProfileRoute,
  LangTournamentsRoute: LangTournamentsRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
  LangAdminCompensationsRoute: LangAdminCompensationsRoute,
  LangAdminMigrateLogosRoute: LangAdminMigrateLogosRoute,
  LangAdminTeamsRoute: LangAdminTeamsRoute,
  LangAdminTournamentsRoute: LangAdminTournamentsRouteWithChildren,
  LangAdminUsersRoute: LangAdminUsersRoute,
  LangTeamsTeamIdRoute: LangTeamsTeamIdRoute,
  LangUsersUserIdRoute: LangUsersUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  LangAdminLiveMatchIdRoute: LangAdminLiveMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
